# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'conjur-concourse-identity'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'az account get-access-token'

# - script: curl -v -H "Metadata:true" 'http://169.254.169.254/metadata/identity/oauth2/token'
#   displayName: curl metadata url

- script: bash -x ./setup.sh eth0 ubuntu
  displayName: 'Setup the conjur and concourse'

- script: bash ./test.sh
  displayName: 'Test conjur with concourse'
