export CONJUR_NAME="conjur-master"
export ADMIN_PASSWORD="CYberark11@@"
export CONJUR_ACCOUNT_NAME="conjur"
export HOST_USERNAME="host/concourse"
export API_KEY_TEAM="apiKeyTeam"
export API_KEY_PIPELINE="apiKeyPipeline"
export API_KEY_VAULT="apiKeyVault"
export IP_INTERFACE="en0"
export CONJUR_HOSTNAME="localhost"

export GIT_BRANCH="conjur-credential-manager-bosh-fix"
export GIT_URL="git@github.com:AndrewCopeland/concourse.git"