version: '2'
services:
  conjur:
    image: captainfluffytoes/dap:11.4.0
    container_name: conjur-master
    restart: always 
    security_opt:
      - seccomp:unconfined
    ports:
      - "443:443"
      - "5432:5432"
      - "1999:1999"

networks:
  default:
    external:
      name: conjur